CONTRACT_ABI = [
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "string", "name": "productId", "type": "string"},
            {"indexed": False, "internalType": "string", "name": "productName", "type": "string"},
            {"indexed": False, "internalType": "string", "name": "batchNumber", "type": "string"},
            {"indexed": True, "internalType": "address", "name": "manufacturer", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "registeredAt", "type": "uint256"},
        ],
        "name": "ProductRegistered",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "string", "name": "productId", "type": "string"},
            {"indexed": True, "internalType": "address", "name": "from", "type": "address"},
            {"indexed": True, "internalType": "address", "name": "to", "type": "address"},
            {"indexed": False, "internalType": "string", "name": "location", "type": "string"},
            {"indexed": False, "internalType": "uint256", "name": "timestamp", "type": "uint256"},
        ],
        "name": "CustodyTransferred",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "string", "name": "productId", "type": "string"},
            {"indexed": True, "internalType": "address", "name": "recalledBy", "type": "address"},
            {"indexed": False, "internalType": "uint256", "name": "timestamp", "type": "uint256"},
        ],
        "name": "ProductRecalled",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True, "internalType": "address", "name": "account", "type": "address"},
            {"indexed": False, "internalType": "string", "name": "name", "type": "string"},
            {"indexed": False, "internalType": "string", "name": "organization", "type": "string"},
        ],
        "name": "ParticipantRegistered",
        "type": "event",
    },
    {
        "inputs": [
            {"internalType": "address", "name": "account", "type": "address"},
            {"internalType": "string", "name": "name", "type": "string"},
            {"internalType": "string", "name": "organization", "type": "string"},
            {"internalType": "bool", "name": "manufacturerAuthorized", "type": "bool"},
            {"internalType": "bool", "name": "custodianAuthorized", "type": "bool"},
        ],
        "name": "registerParticipant",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "productId", "type": "string"},
            {"internalType": "string", "name": "productName", "type": "string"},
            {"internalType": "string", "name": "batchNumber", "type": "string"},
            {"internalType": "string", "name": "manufactureDate", "type": "string"},
            {"internalType": "string", "name": "manufacturerName", "type": "string"},
            {"internalType": "string", "name": "manufacturingLocation", "type": "string"},
            {"internalType": "string", "name": "briefDescription", "type": "string"},
        ],
        "name": "register",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "productId", "type": "string"}],
        "name": "getProductSummary",
        "outputs": [
            {"internalType": "bool", "name": "exists", "type": "bool"},
            {"internalType": "string", "name": "storedProductId", "type": "string"},
            {"internalType": "string", "name": "productName", "type": "string"},
            {"internalType": "string", "name": "batchNumber", "type": "string"},
            {"internalType": "uint256", "name": "registeredAt", "type": "uint256"},
            {"internalType": "enum ProductsOriginChain.ProductStatus", "name": "status", "type": "uint8"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "productId", "type": "string"}],
        "name": "getProductDetails",
        "outputs": [
            {"internalType": "string", "name": "manufactureDate", "type": "string"},
            {"internalType": "string", "name": "manufacturerName", "type": "string"},
            {"internalType": "string", "name": "manufacturingLocation", "type": "string"},
            {"internalType": "string", "name": "briefDescription", "type": "string"},
            {"internalType": "address", "name": "manufacturerAccount", "type": "address"},
            {"internalType": "address", "name": "currentCustodian", "type": "address"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [],
        "name": "getProductCount",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}],
        "name": "getParticipant",
        "outputs": [
            {"internalType": "bool", "name": "exists", "type": "bool"},
            {"internalType": "string", "name": "name", "type": "string"},
            {"internalType": "string", "name": "organization", "type": "string"},
            {"internalType": "bool", "name": "isManufacturer", "type": "bool"},
            {"internalType": "bool", "name": "isCustodian", "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "uint256", "name": "index", "type": "uint256"}],
        "name": "getProductIdAt",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "productId", "type": "string"},
            {"internalType": "address", "name": "newCustodian", "type": "address"},
            {"internalType": "string", "name": "location", "type": "string"},
        ],
        "name": "transferCustody",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "productId", "type": "string"}],
        "name": "recallProduct",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}, {"internalType": "bool", "name": "authorized", "type": "bool"}],
        "name": "setManufacturer",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "address", "name": "account", "type": "address"}, {"internalType": "bool", "name": "authorized", "type": "bool"}],
        "name": "setCustodian",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "productId", "type": "string"}],
        "name": "getCustodyHistoryCount",
        "outputs": [{"internalType": "uint256", "name": "", "type": "uint256"}],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "productId", "type": "string"}, {"internalType": "uint256", "name": "index", "type": "uint256"}],
        "name": "getCustodyRecord",
        "outputs": [
            {"internalType": "address", "name": "from", "type": "address"},
            {"internalType": "address", "name": "to", "type": "address"},
            {"internalType": "string", "name": "location", "type": "string"},
            {"internalType": "uint256", "name": "timestamp", "type": "uint256"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {"inputs": [], "name": "owner", "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"},
    {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "authorizedManufacturers", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
    {"inputs": [{"internalType": "address", "name": "", "type": "address"}], "name": "authorizedCustodians", "outputs": [{"internalType": "bool", "name": "", "type": "bool"}], "stateMutability": "view", "type": "function"},
]
